### PR TITLE
Improve node launching for rosrun

### LINKED ISSUE #33: Running rosjava nodes using rosrun
I noticed that currently there is no "standard" way of calling a rosjava node in the regular ROS way (i.e. `rosrun [package] [node] [params]`). 
After trying this out a little bit, I figured that we are just one step away from there (I updated the [tutorials](http://wiki.ros.org/rosjava_build_tools/Tutorials/indigo/WritingPublisherSubscriber%28Java%29) a bit). Basically, after following the standard steps to create a package, you _can_ use `rosrun` like this:
```
# rosrun [package] [rosjava project] [node class full name]
rosrun rosjava_catkin_package_a my_pub_sub_tutorial com.github.rosjava.rosjava_catkin_package_a.my_pub_sub_tutorial.Talker
```
Because Gradle creates an executable script which calls `RosRun` class in rosjava, with the class to execute as its parameter. 

The problem is that the task `installApp` actually creates two executable scripts inside the package. `rosrun` will then ask the user which one to execute instead of executing it directly.

```
[rosrun] You have chosen a non-unique executable, please pick one of the following:
1) /home/juan/rosjava_test_ws/src/package/project/build/scripts/project
2) /home/juan/rosjava_test_ws/src/package/project/build/install/project/bin/project
3) /home/juan/rosjava_test_ws/src/package/project/build/scripts/project
4) /home/juan/rosjava_test_ws/src/package/project/build/install/project/bin/project
```
If we could just eliminate the scripts under `scripts` directory, `rosrun` would work right away.

Two quick solutions come to my mind. The first one is to tweak the rosjava project [template](https://github.com/rosjava/rosjava_build_tools/blob/kinetic/src/rosjava_build_tools/templates/rosjava_project/build.gradle.in) to delete them, adding something like this:
```
installApp.doLast {
    file('build/scripts').deleteDir()
}
```
The second one would be to use a custom plugin instead of `application` (i.e. `ros-java-application`), which would add the application plugin and a new task ("cleanup" or something like that). Then, tweak the `CMakeLists` to call this new cleanup task after `installApp`. 
Perhaps there is a better option to tweak `installApp` directly from a plugin instead of using the project level `build.gradle`, but I really don't know how to do that in a clean way.

To sum up, this would allow using `rosrun` just like a regular ROS package right after using `catkin_make` and sourcing the workspace.

If this sounds good, I offer myself to create a PR with the fixes. Thoughts?
/cc @adamantivm @ernestmc

### PR DESCRIPTION
**Pull request by gautamjain**
Made the changes that @jubeira mentioned in #33.  

I used the`installDist` task instead of `installApp`.

### CODE REVIEW

**Comment by gautamjain** [comment]
I signed it!

**Comment by jubeira** [comment]
Thanks @gautamjain!
I've gave it a quick try and it didn't work for me; I still see the `scripts` directory after installing. Maybe something changed along the Gradle version since the time I posted that suggested fix?
Have you tried this on your side with a sample package?

**Comment by gautamjain** [comment]
Yes, it worked when I tried it.  The `scripts` directory in the subproject's `build` directory was no longer there. 

This is how I tested.  Let me know if I missed something:

- Cloned the modified `rosjava_build_tools` into my catkin workspace
- ran `catkin_make` and sourced `devel/setup.bash`
- confirmed that `which catkin_create_rosjava_project` and `which catkin_create_rosjava_pkg` was pointing to the scripts under `devel/bin`
- ran the scripts and generated new a package and a project
- Tested by running `./gradlew installDist`.  When I commented out the new tasks, the `scripts` directory would reappear.

Using the default gradle wrapper (4.10.2).

**Comment by gautamjain** [comment]
I also removed the `<<` operator which is deprecated (and not available in Gradle 5.0).

**Comment by gautamjain** [comment]
Hey @jubeira,

If you have any ideas on why it might not be working on your end, let me know.  I can try to replicate on my machine.

**Comment by jubeira** [comment]
Thanks @gautamjain; I've been a bit packed lately but I have this on my radar. I'll give it another shot and let you know!

**Review by jubeira — APPROVED** [review]
Re-tested; this works.

The only detail is that this change does not affect rosjava modules (e.g. pubsub tutorial) don't have this task set, so `rosrun` still can't be used for tutorials inside `rosjava_core`.

**Comment by jubeira** [comment]
Thanks @gautamjain!

**Pull request merged**
