### PR TITLE
Bump version and replace readme file

### PR DESCRIPTION
**Pull request by adamantivm**
@stonier could you please check this? Especially:
 - am I missing anything?
 - is it OK to overwrite this old readme content for now?

### CODE REVIEW

**Comment by stonier** [comment]
> is it OK to overwrite this old readme content for now?

Probably worthwhile documenting what this package actually does for a dev here (i.e. not the user's usage info - that can definitely migrate) so it is easy to see at a glance what you can hack on inside.

* catkin environment hooks to define/initialise variables that support and customise the build
* cmake macro chain that implements the user's `catkin_rosjava_setup()` call
* `catkin_create_xxx` scripts and supporting utilities

**Comment by adamantivm** [comment]
@stonier in order to accelerate the release, what do you think about pushing that task to an issue in the repo (with a kinetic-update tag) to be done after a first release pass? 
Then I can merge this as is and move on, and add that doc you suggest, cleaned-up, on a separate pass.
In order to avoid losing the old readme content permanently, I can add a link to the old readme content in the issue.
We could follow this procedure in general with other such tasks as well. What do you think?

**Comment by stonier** [comment]
> in order to accelerate the release, what do you think about pushing that task to an issue in the repo (with a kinetic-update tag) to be done after a first release pass?

+1

Feel free to merge.

**Comment by adamantivm** [comment]
ok, created #27 to track that.

**Pull request merged**
